export const MENU_SELECTED_ID = 'MENU_SELECTED_ID';
export const GET_MYSERVICES_REQUEST = 'GET_MYSERVICES_REQUEST';
export const GET_MYSERVICES_SUCCESS = 'GET_MYSERVICES_SUCCESS';
export const GET_MYSERVICES_FAILED = 'GET_MYSERVICES_FAILED';